# Generated by Django 5.2 on 2025-04-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'User login'), (2, 'User data update')], verbose_name='Acction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'UserLog',
                'verbose_name_plural': 'UserLogs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
